# for now, s3-tests requires py2
os_type: ubuntu
tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      force-branch: ceph-master
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
